AdventureSeekers/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace AdventureSeekers.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AdventureSeekers/Controllers/User_PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdventureSeekers.Data;
using AdventureSeekers.Models;

namespace AdventureSeekers.Controllers
{
    public class User_PostController : Controller
    {
        private readonly AdventureSeekersContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public User_PostController(AdventureSeekersContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: User_Post
        public async Task<IActionResult> Index()
        {
            var adventureSeekersContext = _context.User_Post.Include(u => u.User_Seekers);
            return View(await adventureSeekersContext.ToListAsync());
        }

        // GET: User_Post/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user_Post = await _context.User_Post
                .Include(u => u.User_Seekers)
                .FirstOrDefaultAsync(m => m.post_id == id);
            if (user_Post == null)
            {
                return NotFound();
            }

            return View(user_Post);
        }

        // GET: User_Post/Create
        public IActionResult Create()
        {
            ViewData["seeker_id"] = new SelectList(_context.User_Seeker, "seeker_id", "seeker_name");
            return View();
        }

        // POST: User_Post/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile? post_image, string post_title, string post_caption, string post_location, string post_categories)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (post_image != null && post_image.Length > 0)
                    {

                        string uniqueFileName = post_image + "_" + post_image.FileName;


                        string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "upload");
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);


                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await post_image.CopyToAsync(fileStream);
                        }


                        User_Post post = new User_Post
                        {
                            post_title = post_title,
                            post_caption = post_caption,
                            post_location = post_location,
                            seeker_id = (int)HttpContext.Session.GetInt32("id"),
                            post_categories = post_categories,
                            post_image = "/upload/" + uniqueFileName,

                        };


                        _context.Add(post);

                        await _context.SaveChangesAsync();

                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {

                        ModelState.AddModelError("image", "Please select an image file.");
                    }

                }
                catch (Exception ex)
                {

                    ModelState.AddModelError("", "Error");

                    return View();
                }
            }
            return RedirectToAction("Index", "Seeker");
        }

        // GET: User_Post/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user_Post = await _context.User_Post.FindAsync(id);
            if (user_Post == null)
            {
                return NotFound();
            }
            ViewData["seeker_id"] = new SelectList(_context.User_Seeker, "seeker_id", "seeker_name", user_Post.seeker_id);
            return View(user_Post);
        }

        // POST: User_Post/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("post_id,post_title,post_caption,post_location,post_categories")] User_Post user_Post)
        {
            if (id != user_Post.post_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user_Post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!User_PostExists(user_Post.post_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["seeker_id"] = new SelectList(_context.User_Seeker, "seeker_id", "seeker_name", user_Post.seeker_id);
            return View(user_Post);
        }

        // GET: User_Post/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user_Post = await _context.User_Post
                .Include(u => u.User_Seekers)
                .FirstOrDefaultAsync(m => m.post_id == id);
            if (user_Post == null)
            {
                return NotFound();
            }

            return View(user_Post);
        }

        // POST: User_Post/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user_Post = await _context.User_Post.FindAsync(id);
            if (user_Post != null)
            {
                _context.User_Post.Remove(user_Post);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool User_PostExists(int id)
        {
            return _context.User_Post.Any(e => e.post_id == id);
        }
    }
}

AdventureSeekers/Controllers/User_SeekerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdventureSeekers.Data;
using AdventureSeekers.Models;

namespace AdventureSeekers.Controllers
{
    public class User_SeekerController : Controller
    {
        private readonly AdventureSeekersContext _context;

        public User_SeekerController(AdventureSeekersContext context)
        {
            _context = context;
        }

        // GET: User_Seeker
        public async Task<IActionResult> Index()
        {
            return View(await _context.User_Seeker.ToListAsync());
        }

        // GET: User_Seeker/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user_Seeker = await _context.User_Seeker
                .FirstOrDefaultAsync(m => m.seeker_id == id);
            if (user_Seeker == null)
            {
                return NotFound();
            }

            return View(user_Seeker);
        }

        // GET: User_Seeker/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: User_Seeker/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("seeker_id,seeker_name,seeker_email,seeker_contact,seeker_address")] User_Seeker user_Seeker)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user_Seeker);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user_Seeker);
        }

        // GET: User_Seeker/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user_Seeker = await _context.User_Seeker.FindAsync(id);
            if (user_Seeker == null)
            {
                return NotFound();
            }
            return View(user_Seeker);
        }

        // POST: User_Seeker/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("seeker_id,seeker_name,seeker_email,seeker_contact,seeker_address")] User_Seeker user_Seeker)
        {
            if (id != user_Seeker.seeker_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user_Seeker);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!User_SeekerExists(user_Seeker.seeker_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user_Seeker);
        }

        // GET: User_Seeker/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user_Seeker = await _context.User_Seeker
                .FirstOrDefaultAsync(m => m.seeker_id == id);
            if (user_Seeker == null)
            {
                return NotFound();
            }

            return View(user_Seeker);
        }

        // POST: User_Seeker/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var user_Seeker = await _context.User_Seeker.FindAsync(id);
            if (user_Seeker != null)
            {
                _context.User_Seeker.Remove(user_Seeker);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool User_SeekerExists(int? id)
        {
            return _context.User_Seeker.Any(e => e.seeker_id == id);
        }
    }
}

AdventureSeekers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdventureSeekers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdventureSeekers.styles.css" asp-append-version="true" />
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="css/custom-styles.css" rel="stylesheet">
    <style>
     
        .bordered {
            display: inline-block;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><strong>Adventure Seekers</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="js/custom-scripts.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AdventureSeekers/Views/Shared/_Layout_Admin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdventureSeekers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdventureSeekers.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Arial', sans-serif;
        }

        .sidebar {
            height: 100vh;
            background-color: #343a40;
            padding-top: 20px;
        }

            .sidebar a {
                color: white;
                padding: 15px;
                text-decoration: none;
                display: block;
            }

                .sidebar a:hover {
                    background-color: #495057;
                }

        .content {
            padding: 20px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><strong>Adventure Seekers Admin</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User_Seeker" asp-action="Index">Seekers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="color:yellow" asp-area="" asp-controller="Home" asp-action="Login">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AdventureSeekers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AdventureSeekers/Views/Shared/_Layout_Seeker.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdventureSeekers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdventureSeekers.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><strong>Adventure Seekers Dashboard</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seeker" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seeker" asp-action="Profile">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seeker" asp-action="Hiking">Hiking</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seeker" asp-action="Bike">Bike Trails</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seeker" asp-action="Extreme">Extreme Adventure</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seeker" asp-action="Gastro">Gastro Delights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seeker" asp-action="Family">Family Trips</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User_Post" asp-action="Create">Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" style="color:yellow" asp-area="" asp-controller="Home" asp-action="Login">Log out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AdventureSeekers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
  
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>